import { Heading, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text fontSize={'x-large'}>worldtrip</Text>
      <Heading fontFamily={'cardTitle'}>Cidade tal</Heading>
    </div>
  )
}

export default Home
